#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Kreator osobnego projektu Supabase dla produkcji (docs/adr/0039, issue #135). Jednorazowy: zakłada projekt
# narzedziownik-prod, ustawia Auth jak w projekcie testowym, wgrywa migracje, zakłada super-admina i demo, przełącza
# zmienne Vercel Production i robi ze starego projektu testowy. Klucze produkcji zapisuje do .env.produkcja.
#
#   scripts/produkcja-supabase.sh

cd "$(dirname "$0")/.."
ENV_FILE=.env.produkcja
DASHBOARD=https://supabase.com/dashboard

# copy_value "opis" VALUE kładzie wartość do schowka, żeby wkleić ją w panelu bez wypisywania na ekran.
copy_value() {
  if command -v pbcopy >/dev/null 2>&1; then printf '%s' "$2" | pbcopy
  elif command -v wl-copy >/dev/null 2>&1; then printf '%s' "$2" | wl-copy
  elif command -v xclip >/dev/null 2>&1; then printf '%s' "$2" | xclip -selection clipboard
  elif command -v clip.exe >/dev/null 2>&1; then printf '%s' "$2" | clip.exe
  else warn "brak schowka; wartość $1 jest w $ENV_FILE"; return; fi
  printf '  %s✓ w schowku:%s %s\n' "$GREEN" "$RESET" "$1"
}

# confirm_run "pytanie" "opis" polecenie… po potwierdzeniu uruchamia polecenie. Odmowa albo błąd nie przerywa
# kreatora, tylko trafia do podsumowania z poleceniem do uruchomienia ręcznie.
confirm_run() {
  local question="$1" what="$2"; shift 2
  if ! confirm "$question"; then SKIPPED+=("$what: $*"); return; fi
  printf '  %s$ %s%s\n' "$DIM" "$*" "$RESET"
  if ! "$@"; then
    SKIPPED+=("$what: nie udało się, popraw i uruchom ręcznie: $*")
    warn "$what: nie udało się. Popraw i uruchom ręcznie: $*"
  fi
}

# Ref obecnego (testowego) projektu z .env.local, jeśli wskazuje Supabase w chmurze.
TEST_REF=$(grep -E '^NEXT_PUBLIC_SUPABASE_URL=' .env.local 2>/dev/null | tail -n1 \
  | sed -nE 's#^NEXT_PUBLIC_SUPABASE_URL=https://([a-z]{20})\.supabase\.co/?$#\1#p' || true)

TOTAL_STAGES=14

banner "NarzędziownikGP: osobny projekt Supabase dla produkcji"

stage "Nowy projekt w Supabase"
say "Zakładasz pusty projekt produkcyjny. Dotychczasowy projekt zostaje testowym."
if [[ -n "$TEST_REF" ]]; then
  note "Projekt testowy z .env.local: $TEST_REF"
else
  step "Nie odczytałem projektu testowego z .env.local. Ref to część adresu https://<ref>.supabase.co."
  until [[ "${TEST_REF:-}" =~ ^[a-z]{20}$ ]]; do ask TEST_REF "Ref obecnego (testowego) projektu:"; done
fi
TEST="$DASHBOARD/project/$TEST_REF"
open_url "$DASHBOARD/new"
step "Organization: ta sama co projekt testowy (DPA Supabase dotyczy organizacji)."
step "Project name: narzedziownik-prod."
step "Database password: Generate a password, zapisz je w menedżerze haseł (będzie potrzebne w etapie 3)."
step "Region: West EU (Ireland), czyli eu-west-1 (ADR 0001). Compute: najmniejszy."
step "Create new project i poczekaj, aż projekt wstanie."
step "Skopiuj ref projektu z adresu panelu: $DASHBOARD/project/<ref> (20 małych liter)."
while :; do
  ask SUPABASE_PROJECT_REF "Ref projektu produkcyjnego:"
  if [[ ! "$SUPABASE_PROJECT_REF" =~ ^[a-z]{20}$ ]]; then warn "To nie wygląda na ref (20 małych liter)."
  elif [[ "$SUPABASE_PROJECT_REF" == "$TEST_REF" ]]; then warn "To ref projektu testowego. Podaj nowy projekt."
  else break; fi
done
write_env SUPABASE_PROJECT_REF "$SUPABASE_PROJECT_REF"
PROD="$DASHBOARD/project/$SUPABASE_PROJECT_REF"

stage "Klucze API projektu produkcyjnego"
say "Bierz te same rodzaje kluczy co w projekcie testowym: anon i service_role (zaczynają się od eyJ)."
open_url "$PROD/settings/api-keys"
step "Zakładka z kluczami legacy (anon, service_role)."
note "Jeśli jej nie ma: sb_publishable_… i sb_secret_… obsługuje supabase-js; logowanie sprawdza etap 12."
write_env NEXT_PUBLIC_SUPABASE_URL "https://$SUPABASE_PROJECT_REF.supabase.co"
step "Skopiuj klucz anon (publiczny)."
ask NEXT_PUBLIC_SUPABASE_ANON_KEY "Klucz anon:"
write_env NEXT_PUBLIC_SUPABASE_ANON_KEY "$NEXT_PUBLIC_SUPABASE_ANON_KEY"
step "Reveal przy service_role i skopiuj (tajny, tylko serwer)."
ask_secret SUPABASE_SERVICE_ROLE_KEY "Klucz service_role:"
write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"

stage "Połączenie z bazą (DATABASE_URL)"
open_url "$PROD?showConnect=true"
step "Connect → Connection string → Transaction pooler (port 6543)."
step "Skopiuj adres i wstaw hasło bazy z etapu 1 w miejsce [YOUR-PASSWORD]."
while :; do
  ask_secret DATABASE_URL "DATABASE_URL:"
  if [[ "$DATABASE_URL" != *"postgres.$SUPABASE_PROJECT_REF:"* || "$DATABASE_URL" != *":6543/"* ]]; then
    warn "Oczekuję puli transakcyjnej projektu produkcyjnego: postgresql://postgres.$SUPABASE_PROJECT_REF:<haslo>@…:6543/postgres"
  elif [[ "$DATABASE_URL" == *"[YOUR-PASSWORD]"* ]]; then warn "Wstaw hasło bazy w miejsce [YOUR-PASSWORD]."
  else break; fi
done
write_env DATABASE_URL "$DATABASE_URL"
note "Klucze produkcji są tylko w $ENV_FILE (poza repo). Do .env.local ich nie przenoś."
pause "Enter, gdy gotowe."

stage "Auth: rejestracja i adresy"
open_url "$PROD/auth/providers"
step "Wyłącz „Allow new users to sign up”. Konta zakłada wyłącznie serwer. Save."
step "Email → minimalna długość hasła: 8 (jak w supabase/config.toml; nowy projekt ma 6). Save."
step "Porównaj resztę strony z projektem testowym:"
open_url "$TEST/auth/providers"
pause "Enter, gdy rejestracja jest wyłączona, a hasło ma co najmniej 8 znaków."
open_url "$PROD/auth/url-configuration"
step "Site URL: https://narzedziownikgp.pl"
step "Redirect URLs, dodaj oba:"
note "    https://narzedziownikgp.pl/auth/confirm"
note "    https://narzedziownik-gp.vercel.app/auth/confirm   (stary adres, naklejki QR)"
pause "Enter, gdy zapisane."

stage "Auth: szablon resetu hasła"
open_url "$PROD/auth/templates"
step "Reset Password."
copy_value "temat" "Reset hasła w NarzędziownikGP"
step "Wklej temat (Subject heading)."
pause "Enter, a skopiuję treść szablonu."
copy_value "treść supabase/templates/recovery.html" "$(cat supabase/templates/recovery.html)"
step "Zamień całą treść (Message body) na tę ze schowka i zapisz."
step "Porównaj pozostałe szablony i powiadomienia e-mail z projektem testowym; zmienione przepisz:"
open_url "$TEST/auth/templates"
pause "Enter, gdy zapisane."

stage "Auth: własny SMTP"
say "Bez własnego SMTP Supabase wysyła e-maile tylko do członków zespołu projektu."
step "Ustawienia projektu testowego do przepisania:"
open_url "$TEST/auth/smtp"
open_url "$PROD/auth/smtp"
step "Enable Custom SMTP i przepisz z projektu testowego: nadawcę (e-mail, nazwa), host, port, użytkownika."
step "Hasło SMTP to klucz API Resend; panel go nie pokazuje. Utwórz klucz w Resend (Sending access) albo weź zapisany."
open_url "https://resend.com/api-keys"
step "Zapisz. Potem w Authentication → Rate Limits ustaw limit e-maili jak w projekcie testowym."
pause "Enter, gdy SMTP zapisany."

stage "Migracje na produkcji"
say "Wgrywam wszystkie migracje z supabase/migrations do pustego projektu produkcyjnego."
say "Supabase CLI pokaże listę migracji i zapyta o potwierdzenie."
confirm_run "Wgrać migracje do $SUPABASE_PROJECT_REF?" "Migracje" npm run db:push:prod
pause "Enter, aby przejść dalej."

stage "Konto super-admina na produkcji"
until [[ "${SUPER_ADMIN_EMAIL:-}" == ?*@?* ]]; do ask SUPER_ADMIN_EMAIL "E-mail super-admina (np. krzysztof@gp-engineering.pl):"; done
say "Skrypt wypisze hasło. Zapisz je w menedżerze haseł, nie pokaże się drugi raz."
confirm_run "Założyć super-admina $SUPER_ADMIN_EMAIL na produkcji?" "Super-admin" \
  npm run super-admin:create:prod -- --email "$SUPER_ADMIN_EMAIL"
pause "Enter, gdy hasło zapisane."

stage "Firma demo na produkcji"
say "Demo dla klientów (/demo) żyje na produkcji (ADR 0039). Zakładam DemoBud z historią."
confirm_run "Założyć demo na produkcji?" "Demo" npm run demo:create:prod
pause "Enter, aby przejść dalej."

stage "Zmienne Vercel: Production na nowy projekt"
say "Cztery zmienne Supabase: Production dostaje klucze nowego projektu, Preview i Development zostają przy starych."
open_url "https://vercel.com/dashboard"
step "Projekt narzedziownik-gp → Settings → Environment Variables."
for key in NEXT_PUBLIC_SUPABASE_URL NEXT_PUBLIC_SUPABASE_ANON_KEY SUPABASE_SERVICE_ROLE_KEY DATABASE_URL; do
  printf '\n'
  say "${BOLD}$key${RESET}"
  step "Przy obecnej zmiennej: ⋯ → Edit, odznacz Production (Preview i Development zostają), Save."
  step "Add New: Key $key, środowisko tylko Production, wartość ze schowka. Tajne klucze jako Sensitive."
  note "Jeśli $key ma już osobny wpis tylko dla Production, wystarczy w nim Edit i wklejenie wartości."
  copy_value "$key" "$(_existing "$key")"
  pause "Enter, gdy $key dodana."
done
if command -v vercel >/dev/null 2>&1; then
  printf '\n'; say "Sprawdzenie (Vercel CLI, same nazwy bez wartości):"
  vercel env ls production 2>/dev/null | grep -E 'SUPABASE|DATABASE_URL' || warn "vercel env ls nie zadziałało; sprawdź w panelu."
  vercel env ls preview 2>/dev/null | grep -E 'SUPABASE|DATABASE_URL' || true
fi
step "Każda z czterech nazw ma być osobno dla Production i osobno dla Preview."
pause "Enter, gdy tak jest."

stage "Ponowne wdrożenie produkcji"
say "Nowe zmienne działają dopiero w nowym wdrożeniu."
open_url "https://vercel.com/dashboard"
step "narzedziownik-gp → Deployments → najnowsze Production (branch main) → ⋯ → Redeploy."
step "Poczekaj na stan Ready."
pause "Enter, gdy produkcja jest wdrożona."

stage "Sprawdzenie produkcji"
open_url "https://narzedziownikgp.pl/logowanie"
step "Zaloguj się jako super-admin hasłem z etapu 8. Panel /super-admin pokazuje tylko firmę demo."
step "Wyloguj się i kliknij „Nie pamiętasz hasła?” dla swojego e-maila: przychodzi e-mail z szablonu,"
step "a link prowadzi na narzedziownikgp.pl i pozwala ustawić hasło (SMTP, szablon i adresy działają)."
step "Otwórz https://narzedziownikgp.pl/demo i wejdź jedną rolą (bez wylogowania)."
PROD_OK=0
if confirm "Wszystko działa?"; then
  PROD_OK=1
else
  SKIPPED+=("Sprawdzenie produkcji: coś nie działa (logowanie, e-mail resetu albo demo)")
  warn "Zapisane w podsumowaniu. W razie potrzeby wróć w Vercel do starych wartości zmiennych i zrób Redeploy."
  pause "Enter, aby przejść dalej."
fi

stage "Stary projekt jako testowy"
if (( PROD_OK )); then
  open_url "$TEST/settings/general"
  step "Nazwa projektu: narzedziownik-test (jeśli jest inna)."
  open_url "$TEST/auth/url-configuration"
  step "Site URL: http://localhost:3000"
  step "Redirect URLs: usuń adresy narzedziownikgp.pl i narzedziownik-gp.vercel.app, zostaw albo dodaj:"
  note "    http://localhost:3000/auth/confirm"
  note "    https://narzedziownik-gp-*.vercel.app/auth/confirm   (podglądy Vercel)"
  note ".env.local i zmienne Preview zostają przy tym projekcie."
  pause "Enter, gdy zapisane."
else
  warn "Pomijam: produkcja nie przeszła sprawdzenia, a stary projekt może jeszcze obsługiwać narzedziownikgp.pl."
  SKIPPED+=("Stary projekt jako testowy: po naprawie produkcji uruchom kreator ponownie albo zrób etap 13 ręcznie")
  pause "Enter, aby przejść dalej."
fi

stage "Umowa powierzenia (DPA) z Supabase"
say "DPA zawiera organizacja Supabase, więc obejmuje każdy jej projekt, także narzedziownik-prod."
open_url "$DASHBOARD/organizations"
step "Organizacja z projektem narzedziownik-prod → ustawienia → dokumenty prawne (Legal Documents) → DPA."
step "Sprawdź, że DPA jest podpisane dla tej organizacji; jeśli nie, podpisz je stamtąd."
if ! confirm "DPA obejmuje organizację z projektem produkcyjnym?"; then
  SKIPPED+=("DPA Supabase dla organizacji z narzedziownik-prod")
fi

copy_value "pusty schowek (bez kluczy produkcji)" ""
finish
say "Od teraz każda migracja: npm run db:push (test), potem npm run db:push:prod przed scaleniem do main."
say "Na koniec odhacz kryteria w issue #135."
printf '\n'
